### ISSUE TITLE
Header blocks do not change from black to white text.

### ISSUE THREAD

**Issue by curiousclinician** [azizultex/Dark-Mode#158]
Hi there.  Header blocks are showing up with black text, and are very hard to work with.

Otherwise, I love this!  Thanks for making it. :)

**Comment by emrikol** [comment]
Hi @curiousclinician!  Is this for header blocks when editing in Gutenberg?

**Comment by peacejet** [comment]
Hello.
I am using the DarkMode plug-in. Just because the issue was posted, I will give feedback.
As you can see from the image, when you use Gutenberg, the titles of the sidebar and header remain black characters. The background is also black, so you won't be able to tell whether the letters are written or not. I would be happy if you could correct it. Thank you.

![image](https://user-images.githubusercontent.com/22917000/66456616-0d98c880-eaa9-11e9-9f99-bc38ba5d21a6.png)

**Comment by emrikol** [comment]
I think the best solution, unfortunately, might be to not load dark mode when using either Gutenberg or the classic editor.  There's a lot of things happening inside the editor(s) that forcing display changes may disrupt from a UX perspective.

Another option might to just use `filter: invert(100%);` to just force invert all of the colors in the editor.  Not really elegant :(

**Comment by peacejet** [comment]
Is that so. That's not elegant. If `filter: invert(100%)` is used, it is not good for the eyes because of the inversion effect of the gradation. You may have to wait until WordPress adopts Dark Mode ... Thank you for teaching me.

**Comment by curiousclinician** [comment]
> Hi @curiousclinician! Is this for header blocks when editing in Gutenberg?

Yessir!  Gutenberg.
